services:
  pizza_frontend:
    container_name: pizza_frontend_pro
    build: .

    volumes:
#      - nginx_volume:/etc/nginx/conf.d
      - static_volume:/app/static/

    ports:
      - 80:80
    environment:
      - CHOKIDAR_USERPOLLING=true