services:
  pizza_frontend:
    container_name: pizza_frontend_pro
    build: .

    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

    ports:
      - 80:80
    environment:
      - CHOKIDAR_USERPOLLING=true