services:
  api:
    container_name: pizza_api_pro
    restart: always
    build: .
    command: gunicorn pizza_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static/
    ports:
      - 8000:8000

    env_file:
      - .env

    depends_on:
      - db
      - redis

  celery:
    container_name: pizza_celery_pro
    build: .
    command: celery -A pizza_django worker --loglevel=info
    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - api
      - redis

  redis:
    container_name: pizza_redis_pro
    image: redis:alpine

  db:
    container_name: pizza_db_pro
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

    env_file:
      - .env

