version: "3"
services:

  web:
    container_name: pizza_frontend
    build: pizza_vue

    volumes:
      - /pizza_vue:/app/pizza_vue
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USERPOLLING=true



  api:
    container_name: pizza_api
    restart: always
    build: .

    volumes:
      - .:/app
    ports:
      - 8000:8000

    env_file:
      - .env

    depends_on:
      - db
      - redis

    command: python manage.py runserver 0.0.0.0:8000

  celery:
    container_name: pizza_celery
    build: .
    command: celery -A pizza_django worker --loglevel=info
    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - api
      - redis

  redis:
    container_name: pizza_redis
    image: redis:alpine

  db:
    container_name: pizza_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

    env_file:
      - .env

volumes:
  postgres_data: