# Generated by Django 4.0.1 on 2022-01-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
    ]
