# Generated by Django 4.0.1 on 2022-01-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_price_remove_product_price_topping_size_sauce_and_more'),
        ('order', '0004_remove_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sauce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.sauce'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.topping'),
        ),
    ]
