# Generated by Django 4.0.1 on 2022-01-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_sauce_orderitem_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='order_price',
        ),
    ]
