# Generated by Django 4.0.1 on 2022-01-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_price_orderitem_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_price',
            new_name='price',
        ),
    ]
